-- Manual schema change (Flyway not used). Run in MySQL when JPA_DDL_AUTO=validate.
-- Phase 1: inventory-backed voucher codes (batch upload + integration issue).

CREATE TABLE IF NOT EXISTS voucher_batch (
  id                        BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  batch_uid                 VARCHAR(128) NOT NULL,
  tenant_id                 VARCHAR(64) NOT NULL,
  programme_uid             VARCHAR(64) NOT NULL,
  catalog_reward_uid        VARCHAR(64) NOT NULL,
  partner_uid               VARCHAR(128),
  original_filename         VARCHAR(512) NOT NULL,
  file_size_bytes           BIGINT,
  file_sha256               VARCHAR(64),
  column_mapping_json       JSON,
  status                    ENUM('PROCESSING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'PROCESSING',
  total_rows_uploaded       INT NOT NULL DEFAULT 0,
  imported_count            INT NOT NULL DEFAULT 0,
  duplicate_count           INT NOT NULL DEFAULT 0,
  expired_count             INT NOT NULL DEFAULT 0,
  invalid_count             INT NOT NULL DEFAULT 0,
  error_count               INT NOT NULL DEFAULT 0,
  error_report_json         JSON,
  uploaded_by               VARCHAR(255) NOT NULL,
  uploaded_at               DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  completed_at              DATETIME(6),
  UNIQUE KEY uk_batch_uid (batch_uid),
  KEY idx_tenant_programme (tenant_id, programme_uid),
  KEY idx_tenant_catalog (tenant_id, catalog_reward_uid),
  KEY idx_tenant_file_sha (tenant_id, file_sha256),
  KEY idx_status (status),
  KEY idx_created (uploaded_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS voucher_inventory (
  id                        BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  inventory_uid             VARCHAR(128) NOT NULL,
  tenant_id                 VARCHAR(64) NOT NULL,
  programme_uid             VARCHAR(64) NOT NULL,
  catalog_reward_uid        VARCHAR(64) NOT NULL,
  batch_uid                 VARCHAR(128) NOT NULL,
  code_hash                 VARCHAR(64) NOT NULL,
  code_ciphertext             VARCHAR(1024) NOT NULL,
  pin_hash                  VARCHAR(64),
  pin_ciphertext            VARCHAR(512),
  partner_sku               VARCHAR(128),
  face_value                DECIMAL(18, 4),
  currency                  CHAR(3),
  expires_at                DATETIME(6),
  status                    ENUM('AVAILABLE', 'RESERVED', 'ISSUED', 'REDEEMED', 'EXPIRED', 'QUARANTINED', 'VOID')
                           NOT NULL DEFAULT 'AVAILABLE',
  reserved_until            DATETIME(6),
  customer_id               VARCHAR(128),
  redemption_id             VARCHAR(128),
  ledger_id                 BIGINT UNSIGNED,
  issued_at                 DATETIME(6),
  partner_confirmation_ref  VARCHAR(255),
  redeemed_at               DATETIME(6),
  extra_metadata_json       JSON,
  created_at                DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at                DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uk_inventory_uid (inventory_uid),
  UNIQUE KEY uk_tenant_code_hash (tenant_id, code_hash),
  UNIQUE KEY uk_redemption_id (redemption_id),
  KEY idx_issue (tenant_id, programme_uid, catalog_reward_uid, status, created_at),
  KEY idx_batch (batch_uid),
  KEY idx_customer (tenant_id, customer_id, status),
  KEY idx_status_expires (status, expires_at),
  KEY idx_ledger_ref (ledger_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS voucher_redemption_audit (
  id                        BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  audit_uid                 VARCHAR(128) NOT NULL,
  tenant_id                 VARCHAR(64) NOT NULL,
  inventory_uid             VARCHAR(128),
  redemption_id             VARCHAR(128) NOT NULL,
  ledger_id                 BIGINT UNSIGNED,
  customer_id               VARCHAR(128) NOT NULL,
  event_type                ENUM('ISSUED', 'RESERVED', 'RELEASED', 'EXPIRED', 'QUARANTINED', 'VOIDED', 'REDEEMED') NOT NULL,
  actor                     VARCHAR(255),
  reason                    TEXT,
  metadata_json             JSON,
  created_at                DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY uk_audit_uid (audit_uid),
  KEY idx_tenant_customer (tenant_id, customer_id, created_at),
  KEY idx_redemption_id (redemption_id),
  KEY idx_inventory_uid (inventory_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
