package com.loyaltyos.campaigns.enums;

public enum DropReason {
    LOWER_PRIORITY_IN_GROUP,
    LOWER_VALUE_IN_GROUP,
    BUDGET_EXHAUSTED,
    CUSTOMER_CAP_REACHED,
    TOTAL_PARTICIPATION_CAP_REACHED,
    GLOBAL_CAP_HIT,
    ELIGIBILITY_FAILED,
    CUSTOMER_NOT_IN_TARGET_LIST,
    MERCHANT_SCOPE_MISMATCH,
    NOT_STACKABLE_CONFLICT
}
